menu_item_extras.settings:
  type: config_object
  mapping:
    allowed_menus:
      type: sequence
      label: 'Allowed menus for Expanded functionality'
      sequence:
        type: string
        label: 'Menu ID'
    menu_as_bundle:
      type: boolean
      label: 'Use one type per menu or not'
